webtalk_init -webtalk_dir C:/Users/johnc/Documents/Sch Stuff/Year 2/Sem 1/EE2026/Project/SoundDisplay/SoundDisplay/SoundDisplay.sim/sim_1/behav/xsim/xsim.dir/OLED_button_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Oct  9 23:21:54 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d6c89383-6858-4d9b-885c-58fa9c2f7f0e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0917254c695c4cb5998f17b74e73445e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5700U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1797 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "70208975 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16616_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2764190903 -regid "" -xml C:/Users/johnc/Documents/Sch Stuff/Year 2/Sem 1/EE2026/Project/SoundDisplay/SoundDisplay/SoundDisplay.sim/sim_1/behav/xsim/xsim.dir/OLED_button_test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/johnc/Documents/Sch Stuff/Year 2/Sem 1/EE2026/Project/SoundDisplay/SoundDisplay/SoundDisplay.sim/sim_1/behav/xsim/xsim.dir/OLED_button_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/johnc/Documents/Sch Stuff/Year 2/Sem 1/EE2026/Project/SoundDisplay/SoundDisplay/SoundDisplay.sim/sim_1/behav/xsim/xsim.dir/OLED_button_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
